# -*- coding: utf-8 -*-
"""week01_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fH4aD4ty3wVWUsXqDJomko4vyLDo9Uc
"""

number = int(input())
is_prime = True

if number <= 1:
  is_prime = False
else:
  for i in range(2, number):
    if number % i == 0:
      is_prime = False
      break

if is_prime:
  print(f'{number} is prime number~')
else:
  print(f'{number} is NOT prime number!')

# 2
# 11
# 2 3 5 7 11
a, b = map(int, input().split())
for i in range(a, b+1):
    is_prime = True

    if i <= 1:
        is_prime = False
    else:
        for k in range(2, i):
            if i % k == 0:
                is_prime = False
                break
        if is_prime:
            print(i, end=' ')